window.AH_TEMPLATES = (function() {
    const SERVER_RU = {
        "Tucson": "Туксон",
        "Scottdale": "Скоттдейл",
        "Chandler": "Чандлер",
        "Brainburg": "Брейнбург"
    };

    return function(CONFIG) {
        const SERVER_NAME_RU = SERVER_RU[CONFIG.server] || CONFIG.server;
        
        function g(maleText, femaleText) {
            return CONFIG.gender === 'Female' ? femaleText : maleText;
        }

        const EXTRA_OPTIONS = [
            { title: "Признать виновным (Гражд) в УК", text: `<br>Признать гражданина - Nickname виновным в нарушении статьи ХХ.Х Уголовного Кодекса штата ${SERVER_NAME_RU}.` },
            { title: "Признать не виновным (Гражд) в УК", text: `<br>Признать гражданина - Nickname невиновным и снять все обвинения.` },
            { title: "Признать действия неправомерными (Гражд)", text: `<br>Признать действия гражданина - Nickname неправомерными в связи с нарушением статьи ХХ.ХХ ZAKON.` },
            { title: "Признать действия правомерными (Гражд)", text: `<br>Признать действия гражданина - Nickname правомерными` },
            { title: "Признать виновным (Сотрудника) в УК", text: `<br>Признать ${g('сотрудника', 'сотрудницу')} ${CONFIG.organization} - Nickname виновным в нарушении статьи ХХ.Х Уголовного Кодекса штата ${SERVER_NAME_RU}.` },
            { title: "Признать виновным (Сотрудника) в Дисц. проступке", text: `<br>Признать ${g('сотрудника', 'сотрудницу')} ${CONFIG.organization} - Nickname виновным в нарушении статьи ХХ.Х устава ${CONFIG.organization} штата ${SERVER_NAME_RU}` },
            { title: "Признать не виновным (Сотрудника) в УК", text: `<br>Признать ${g('сотрудника', 'сотрудницу')} ${CONFIG.organization} - Nickname невиновным и снять все обвинения.` },
            { title: "Признать действия неправомерными (Сотрудника)", text: `<br>Признать действия ${g('сотрудника', 'сотрудницы')} ${CONFIG.organization} - Nickname неправомерными в связи с нарушением статьи ХХ.ХХ ZAKON.` },
            { title: "Признать действия правомерными (Сотрудника)", text: `<br>Признать действия ${g('сотрудника', 'сотрудницы')} ${CONFIG.organization} - Nickname правомерными` },
            { title: "Вписать 1 выговор", text: `<br>Вписать в личное дело вышеупомянутого ${g('сотрудника', 'сотрудницы')} один дисциплинарный выговор.` },
            { title: "Вписать 2 выговора", text: `<br>Вписать в личное дело вышеупомянутого ${g('сотрудника', 'сотрудницы')} два дисциплинарных выговора.` },
            { title: "Уволить с должности", text: `<br>Уволить вышеупомянутого ${g('сотрудника', 'сотрудницы')} с занимаемой должности без возможности на восстановление.` },
            { title: "Провести беседу", text: `<br>Провести вышеупомянутому ${g('сотруднику', 'сотруднице')} беседу на тему ТЕМА.` },
            { title: "Снять один выговор", text: `<br>Снять один дисциплинарный выговор вышеупомянутому ${g('сотруднику', 'сотруднице')}.` },
            { title: "Снять два выговора", text: `<br>Снять два дисциплинарных выговора вышеупомянутому ${g('сотруднику', 'сотруднице')}.` },
            { title: "Восстановление на должность", text: `<br>Восстановить вышеупомянутого ${g('гражданина', 'гражданку')} в ${CONFIG.organization} на X порядковую должность.` },
            { title: "Выписать ордер (Арест)", text: `<br>Выписать ордер на арест на вышеупомянутого ${g('гражданина', 'гражданку')} по статье ХХ.Х Уголовного Кодекса штата ${SERVER_NAME_RU}.` },
            { title: "Выписать ордер (Обыск)", text: `<br>Выписать ордер на обыск на вышеупомянутого ${g('гражданина', 'гражданку')} в связи с ....` },
            { title: "Провести правомерный арест", text: `<br>Провести правомерный арест вышеупомянутого ${g('гражданина', 'гражданку')}.` },
            { title: "Провести правомерный обыск", text: `<br>Провести правомерный обыск вышеупомянутого ${g('гражданина', 'гражданку')}.` },
            { title: "Выпустить из ТСР", text: `<br>Выпустить из Тюрьмы Строгого Режима вышеупомянутого ${g('гражданина', 'гражданку')}, случае если таковой там находится.` },
            { title: "Штраф", text: `<br>Назначить штраф вышеупомянутому ${g('гражданину', 'гражданке')} виде $SUMM.` },
            { title: "Выписать компенсацию", text: `<br>Назначить компенсацию ${g('гражданину', 'гражданке')} - Nickname, ответчик/истец обязан в течении 48 часов оплатить компенсацию.` },
            { title: "Снять розыск", text: `<br>Вынести с базы данных разыскиваемых ${g('гражданина', 'гражданку')} NickName` },
            { title: "Компенсация от Руководства", text: `<br>Обязать руководство ${CONFIG.organization} выплатить компенсацию истцу в размере SUMMA в течении 48 часов с момента публикации постановления.` },
            { title: "Закрыть дело", text: "<br><br>Закрыть дело по решению суда." }
        ];

        const ORG_NAMES = [
            { title: "Government", text: "Government", color: "#f1c40f" },
            { title: "Collegium Of Lawyers", text: "Collegium Of Lawyers", color: "#f1c40f" },
            { title: "Insurance Company", text: "Insurance Company", color: "#f1c40f" },
            { title: "Licensing Center", text: "Licensing Center", color: "#f1c40f" },
            { title: "Federal Bureau of Investigation", text: "Federal Bureau of Investigation", color: "#3498db" },
            { title: "Los-Santos Police Department", text: "Los-Santos Police Department", color: "#3498db" },
            { title: "San-Fierro Police Department", text: "San-Fierro Police Department", color: "#3498db" },
            { title: "Las-Venturas Police Department", text: "Las-Venturas Police Department", color: "#3498db" },
            { title: "Red County Sheriff Department", text: "Red County Sheriff Department", color: "#3498db" },
            { title: "Los-Santos Army", text: "Los-Santos Army", color: "#c27c0e" },
            { title: "San-Fierro Army", text: "San-Fierro Army", color: "#c27c0e" },
            { title: "Maximum Security Prison", text: "Maximum Security Prison", color: "#c27c0e" },
            { title: "Los-Santos Medical Center", text: "Los-Santos Medical Center", color: "#e91e63" },
            { title: "San-Fierro Medical Center", text: "San-Fierro Medical Center", color: "#e91e63" },
            { title: "Las-Venturas Medical Center", text: "Las-Venturas Medical Center", color: "#e91e63" },
            { title: "Jefferson Medical Center", text: "Jefferson Medical Center", color: "#e91e63" },
            { title: "Fire Department", text: "Fire Department", color: "#ff0000" },
            { title: "Radiocentre Los-Santos", text: "Radiocentre Los-Santos", color: "#ffa500" },
            { title: "Radiocentre San-Fierro", text: "Radiocentre San-Fierro", color: "#ffa500" },
            { title: "Radiocentre Las-Venturas", text: "Radiocentre Las-Venturas", color: "#ffa500" }
        ];

        const REPLIES = {
            verdict: {
                title: 'Форма Вердикта (С правилом)',
                needsVerdictForm: true,
                text: function(playerName, punishment, reason, ruleText, logLine) {
                    let res = `[CENTER][FONT=verdana][SIZE=5]<p>Здравствуйте.</p><p>Игрок ${playerName} получит ${punishment} за ${reason}.</p>`;
                    if (logLine) {
                        res += `<p>[QUOTE]${logLine}[/QUOTE]</p>`;
                    } else if (ruleText && (ruleText.toLowerCase().includes('офф от') || ruleText.toLowerCase().includes('выход из игры'))) {
                        res += `<p>[QUOTE]Вставьте строку лога сюда[/QUOTE]</p>`;
                    }
                    if (ruleText) {
                        res += `<p>Пункт правил: ${ruleText}</p>`;
                    }
                    res += `<p>Закрыто.</p>[/SIZE][/FONT][/CENTER]`;
                    return res;
                }
            },
            jbadm: { title: 'Ответ ЖБАДМ', text: `[CENTER][SIZE=5][FONT=verdana]<p>Здравствуйте, уважаемый игрок.</p><p>Вы получили наказание за Указываете причину.</p><p>Ниже предоставляю доказательства вашего нарушения.</p><br>Доказательства: Ссылка на видео/скрин с чата</br>[/FONT][/SIZE][/CENTER][HR][/HR]<p>[CENTER][SIZE=5][FONT=verdana]Правила проекта: Ссылка на правила</p><p>Пункт с правил: Пункт который нарушил игрок.</p><br>Ожидайте ответ от старшей администрации.</br>[/FONT][/SIZE][/CENTER]` },
            jbadmError: { title: 'Ответ ЖБАДМ (ошибка)', text: `[CENTER][FONT=verdana][SIZE=5]<p>Здравствуйте, уважаемый игрок.</p><p>Вы были ошибочно наказаны мной, прошу прощения. Более такого не повторится.</p><p>Вам снимут бан/выпустят из деморгана/снимут мут.</p><p>Спасибо за понимание.</p><p>Ожидайте ответ от старшей администрации.</p>[/SIZE][/FONT][/CENTER]` },
            inReview: { title: 'ЖБ на рассмотрении', text: `[CENTER][SIZE=5][FONT=verdana]<p>Здравствуйте.</p><p>Жалоба на рассмотрении.</p>[/FONT][/SIZE][/CENTER]` },
            requestProof: { title: 'Запрос опровержения', text: function(today) { return `[CENTER][SIZE=5][FONT=verdana]<p>Опру от игрока - X_X</p><p>Точное время запроса: ${today}</p>[/FONT][/SIZE][/CENTER]`; } },
            wrongFormat: { title: 'Не по форме', text: `[CENTER][SIZE=5][FONT=verdana]<p>Здравствуйте.</p><p>Жалоба составлена не по форме.</p><p>[SPOILER="Форма ответа"] Рекомендации при написании жалобы: [URL='https://forum.arizona-rp.com/threads/5869787/'][U][COLOR=rgb(84, 172, 210)]Click[/COLOR][/U][/URL]<p>Форма для заголовка темы:</p><p>Жалоба на игрока: TEXT | Причина: TEXT | Фракция: TEXT</p><p>Форма для заявки:</p><p>Ваш игровой ник: TEXT </p><p>Игровой ник нарушителя: TEXT </p><p>Суть жалобы: TEXT</p> <p>Доказательства: "URL" + тайм-код нарушения, если запись идет дольше 30 секунд </p><p>Я готов нести ответственность в случае обмана вплоть до вечной блокировки: Да/Нет</p> [/SPOILER]</p><p>Закрыто.</p>[/FONT][/SIZE][/CENTER]` },
            transferred: { title: 'Передано ст. адм', text: `[CENTER][SIZE=5][FONT=verdana]<p>Здравствуйте.</p><p>Жалоба передана старшей администрации.</p>[/FONT][/SIZE][/CENTER]` },
            ghettoDefault: { title: 'Написать жалобу на игрока', text: `<br>[SIZE=5][FONT=courier new]Жалоба на игрока: "TEXT" | Причина: "TEXT" | Фракция: "TEXT"</br><br><p>Ваш игровой ник: ${CONFIG.NonRPnickname}</p><p>Игровой ник нарушителя: "TEXT"</p><p>Суть жалобы: "TEXT"</p><p>Доказательства: "URL" + тайм-код нарушения, если запись идет дольше 30 секунд.</p><p>Я готов нести ответственность в случае обмана вплоть до вечной блокировки: Да[/FONT][/SIZE]</p></br>` },
            pdDefault: { title: 'Опра в иске (от лица ПД)', text: `[CENTER][SIZE=5][FONT=courier new]<p>To the State Court of ${CONFIG.server}</p><br>Federal Bureau of Investigation Field Office | Los Santos Police Department | Las Venturas Police Department | San Fierro Police Department | Red County Sheriff's Department ([COLOR=rgb(184, 49, 47)]выбрать свою[/COLOR])</br><br>От ${g('сотрудника', 'сотрудницы')} ${CONFIG.organization} - ${CONFIG.nickname}</br><br>Рассмотрев обвинения в свою сторону, прикладываю соответствующие доказательства по делу и даю краткое пояснения ситуации:</br><br>К своим словам прикладываю доказательства:</br>[/FONT][/SIZE][/CENTER] [SIZE=5][FONT=courier new][/FONT][/SIZE] [CENTER][SIZE=5][FONT=courier new]<p>[SPOILER="Тайм коды"] Ваши тайм коды к видео [/SPOILER]</p><br>Я, ${g('гражданин', 'гражданка')} штата ${SERVER_NAME_RU}, торжественно клянусь, что предоставленные мной факты не являются сфальсифицированы и являются полностью правдивыми.</br>[/FONT][/SIZE][/CENTER] [RIGHT][SIZE=5][FONT=courier new]<br>Дата: чч.мм.гггг </br><p>Подпись: ${CONFIG.signature}</p>[/FONT][/SIZE][/RIGHT]` },
            playerDefault: { title: 'Подать исковое заявление', text: `[CENTER][SIZE=5][FONT=courier new]<p>Исковое заявление № XXYYFFFF</p>[/FONT][/SIZE][/CENTER] [SIZE=5][FONT=courier new]<p>Я, ${g('гражданин', 'гражданка')} штата ${SERVER_NAME_RU}, ВАШЕ ИМЯ И ФАМИЛИЯ, подаю исковое заявление на ${g('гражданина', 'гражданку')} штата ${SERVER_NAME_RU} - ИМЯ И ФАМИЛИЯ ОБВИНЯЕМОГО.</p><p>Причина вашего заявления, ваши требования:</p><p>Имя Фамилия обвиняемого: X </p><p>Материалы дела:</p>[/FONT][/SIZE] [CENTER][SIZE=5][FONT=courier new] <br>Контактные данные [Discord / VK]:</br><p>Документ, удостоверяющий вашу личность [Паспорт, если в ТСР -> /stats]:</p>[/FONT][/SIZE][/CENTER] [RIGHT][SIZE=5][FONT=courier new]<br>Дата: xx.xx.xxxx</br><p>Подпись: ____[SIZE=5][FONT=courier new]_[SIZE=5][FONT=courier new]_[SIZE=5][FONT=courier new]_[/FONT][/SIZE][/FONT][/SIZE][/FONT][/SIZE][/FONT][/SIZE][/RIGHT]</p>` },
            lawyerPetition: { title: 'Ходатайство от адвоката', text: `<p>[CENTER][FONT=courier new][SIZE=5]Ходатайство [COLOR=rgb(250, 197, 28)]№00000001[/COLOR][/SIZE][/FONT][/CENTER]</p><br>[RIGHT][FONT=courier new][SIZE=5]From - [/SIZE][COLOR=rgb(250, 197, 28)][SIZE=5]${CONFIG.nickname}[/SIZE][/COLOR] [SIZE=5]<p>Attorney To - [COLOR=rgb(250, 197, 28)]xxx[/COLOR], Judge</p>[/SIZE][/FONT][/RIGHT]</br> [FONT=courier new][SIZE=5]Я, частный адвокат моего клиента [COLOR=rgb(250, 197, 28)]ххх[/COLOR].[/SIZE][/FONT] [SIZE=5][FONT=courier new]Ходатайствую: [COLOR=rgb(250, 197, 28)]ххх[/COLOR].[/FONT][/SIZE] [FONT=courier new][SIZE=5][/SIZE][/FONT] <br>[RIGHT][FONT=courier new][SIZE=5]Дата - [COLOR=rgb(250, 197, 28)]чч.мм.гггг[/COLOR]<p>Подпись - [COLOR=rgb(250, 197, 28)]_______</p>[/COLOR][/SIZE][/FONT][/RIGHT]</br>` },
            motionPlaintiff: { title: 'Ходатайство от истца', text: `<br>[CENTER][FONT=courier new][SIZE=5]Ходатайство [COLOR=rgb(250, 197, 28)]№00000001[/COLOR][/SIZE][/FONT][/CENTER]<p>[RIGHT][SIZE=5][FONT=courier new]From - ${CONFIG.nickname}[/FONT][/SIZE]</p><p>[FONT=courier new][SIZE=5]Plaintiff To - [COLOR=rgb(250, 197, 28)]xxx[/COLOR], Judge[/SIZE][/FONT][/RIGHT]</p></br><br>[SIZE=5][FONT=courier new]Я, истец данного дела, ходатайствую: ххх.[/FONT]</br><br><p>[RIGHT][SIZE=5][FONT=courier new]Дата - [COLOR=rgb(250, 197, 28)]чч.мм.гггг[/COLOR][/FONT][/SIZE]</p><p>[FONT=courier new][SIZE=5]Подпись - [COLOR=rgb(250, 197, 28)]_______[/COLOR][/SIZE][/FONT][/RIGHT]</p></br>` },
            motionDefendant: { title: 'Ходатайство от ответчика', text: `<br><p>[CENTER][FONT=courier new][SIZE=5]Ходатайство [COLOR=rgb(250, 197, 28)]№00000001[/COLOR][/SIZE][/FONT][/CENTER]</p><p>[RIGHT][FONT=courier new][SIZE=5]From - [COLOR=rgb(250, 197, 28)]${CONFIG.nickname}[/COLOR]</p><p>Defendant To - [COLOR=rgb(250, 197, 28)]xxx[/COLOR], Judge[/SIZE][/FONT][/RIGHT]</p></br><br>[SIZE=5][FONT=courier new] Я, ответчик данного дела, ходатайствую: ххх. [/FONT][/SIZE]</br><br><p>[RIGHT][FONT=courier new][SIZE=5]Дата - [COLOR=rgb(250, 197, 28)]чч.мм.гггг[/COLOR]</p>Подпись - [COLOR=rgb(250, 197, 28)]_______[/COLOR][/SIZE][/FONT][/RIGHT]</p></br>` },
            addmotionDefendant: { title: 'Добавление к ходатайству от ответчика', text: `<br><p>[CENTER][FONT=courier new][SIZE=5]Добавление к ходатайству [COLOR=rgb(250, 197, 28)]№00000001[/COLOR][/SIZE][/FONT][/CENTER]</p><p>[RIGHT][FONT=courier new][SIZE=5]From - [COLOR=rgb(250, 197, 28)]${CONFIG.nickname}[/COLOR]</p><p>Defendant To - [COLOR=rgb(250, 197, 28)]xxx[/COLOR], Judge[/SIZE][/FONT][/RIGHT]</p></br><br>[SIZE=5][FONT=courier new] Я, ответчик данного дела, предоставляю Nick Name:ххх. [/FONT][/SIZE]</br><br><p>[RIGHT][FONT=courier new][SIZE=5]Дата - [COLOR=rgb(250, 197, 28)]чч.мм.гггг[/COLOR]</p><p>Подпись - [COLOR=rgb(250, 197, 28)]_______[/COLOR][/SIZE][/FONT][/RIGHT]</p></br>` },
            addmotionPlaintiff: { title: 'Добавление к ходатайству от истца', text: `<br><p>[CENTER][FONT=courier new][SIZE=5]Добавление к ходатайству [COLOR=rgb(250, 197, 28)]№00000001[/COLOR][/SIZE][/FONT][/CENTER]</p><p>[RIGHT][FONT=courier new][SIZE=5]From - [COLOR=rgb(250, 197, 28)]${CONFIG.nickname}[/COLOR]</p><p>Plaintiff To - [COLOR=rgb(250, 197, 28)]xxx[/COLOR], Judge[/SIZE][/FONT][/RIGHT]</p></br><br>[SIZE=5][FONT=courier new] Я, истец данного дела, предоставляю Nick Name: ххх. [/FONT][/SIZE]</br><br><p>[RIGHT][FONT=courier new][SIZE=5]Дата -[/SIZE][COLOR=rgb(250, 197, 28)][SIZE=5] [/SIZE][/COLOR][SIZE=5][COLOR=rgb(250, 197, 28)]чч.мм.гггг[/COLOR]</p><p> Подпись - [COLOR=rgb(250, 197, 28)]_______[/COLOR][/SIZE][/FONT][/RIGHT]</p></br>` },
            addlawyerPetition: { title: 'Добавление к ходатайству от адвоката', text: `<br><p>[CENTER][FONT=courier new][SIZE=5]Добавление к ходатайству [COLOR=rgb(250, 197, 28)]№00000001[/COLOR][/SIZE][/FONT][/CENTER]</p><p>[RIGHT][FONT=courier new][SIZE=5]From - [COLOR=rgb(250, 197, 28)]${CONFIG.nickname}[/COLOR]</p><p> Attorney To - [COLOR=rgb(250, 197, 28)]xxx[/COLOR], Judge[/SIZE][/FONT][/RIGHT]</p></br><br>[SIZE=5][FONT=courier new] Я, частный адвокат моего клиента ххх, предоставляю Nick Name:ххх. [/FONT][/SIZE]</br><br><p>[RIGHT][FONT=courier new][SIZE=5]Дата - [COLOR=rgb(250, 197, 28)]чч.мм.гггг[/COLOR]</p><p>Подпись - [COLOR=rgb(250, 197, 28)]_______[/COLOR][/SIZE][/FONT][/RIGHT]</p></br>` },
            addlawyerPetitionFromPlaintiff: { title: 'Ходатайство о добавл. адвоката (Истец)', text: `<br><p>[CENTER][FONT=courier new][SIZE=5]Ходатайство [COLOR=rgb(250, 197, 28)]№00000001[/COLOR][/SIZE][/FONT][/CENTER]</p><p>[RIGHT][FONT=courier new][SIZE=5]From - [COLOR=rgb(250, 197, 28)]${CONFIG.nickname}[/COLOR]</p><p> Plaintiff To - [COLOR=rgb(250, 197, 28)]xxx[/COLOR], Judge[/SIZE][/FONT][/RIGHT]</p></br><br><p>[SIZE=5][FONT=courier new]Я, истец данного дела, ходатайствую: </p><p>1. Назначаю себе частного адвоката Nick Name.</p><p>1.1 К доказательствам, прикрепляю договор - LINK [/FONT][/SIZE]</p></br><br><p>[RIGHT][SIZE=5][FONT=courier new]Дата - [COLOR=rgb(250, 197, 28)]чч.мм.гггг[/COLOR]</p><p>Подпись - [COLOR=rgb(250, 197, 28)]_______[/COLOR][/FONT][/SIZE][/RIGHT]` },
            addDefendantPetitionFromPlaintiff: { title: 'Ходатайство о добавл. адвоката (Ответчик)', text: `<br><p>[CENTER][FONT=courier new][SIZE=5]Ходатайство [COLOR=rgb(250, 197, 28)]№00000001[/COLOR][/SIZE][/FONT][/CENTER]</p><p>[RIGHT][FONT=courier new][SIZE=5]From - [COLOR=rgb(250, 197, 28)]${CONFIG.nickname}[/COLOR]</p><p>Defendant To - [COLOR=rgb(250, 197, 28)]xxx[/COLOR], Judge[/SIZE][/FONT][/RIGHT] [FONT=courier new][/FONT]</p></br><br><p>[SIZE=5][FONT=courier new]Я, ответчик данного дела, ходатайствую: </p><p>1. Назначаю себе частного адвоката Nick Name. </p><p>1.1 К доказательствам, прикрепляю договор - LINK [/FONT][/SIZE]</p></br><br><p>[RIGHT][SIZE=5][FONT=courier new]Дата - [COLOR=rgb(250, 197, 28)]чч.мм.гггг[/COLOR]</p><p>Подпись - [COLOR=rgb(250, 197, 28)]ххх[/COLOR][/FONT][/SIZE][/RIGHT]</p></br>` },
            takeLawsuit: { title: 'Принятие иска', text: function(today, lawsuitNum) { const dateOnly = today.split(',')[0]; return `<br><p>[CENTER][FONT=courier new][IMG width="274px"]https://i.imgur.com/y77Cwct.png[/IMG]</p> <p>[IMG]https://i.imgur.com/03s50C0.png[/IMG][/FONT][/CENTER]</p> <p>[RIGHT][FONT=courier new]Судейская коллегия штата ${CONFIG.server}</p> <p>${CONFIG.rang} ${CONFIG.nickname}[/FONT][/RIGHT]</p></br> <br><p>[CENTER] [FONT=courier new]Доброго времени суток.</p> <p>Принял${g('ся', 'ась')} рассматривать дело №${lawsuitNum}, ожидайте ответа.</p> [/FONT] [/CENTER]</p></br> <br><p>[RIGHT][FONT=courier new]${dateOnly}</p> <p>Подпись: ${CONFIG.signature}[/FONT][/RIGHT]</p></br>`; } },
            requestExplanations: { title: 'Запрос опровержения (24 часа)', text: function(today, lawsuitNum) { const dateOnly = today.split(',')[0]; return `<br><p>[CENTER][FONT=courier new][IMG width="274px"]https://i.imgur.com/y77Cwct.png[/IMG]</p> <p>[IMG]https://i.imgur.com/03s50C0.png[/IMG][/FONT][/CENTER]</p> <p>[RIGHT][FONT=courier new]Судейская коллегия штата ${CONFIG.server}</p> <p>${CONFIG.rang} ${CONFIG.nickname}[/FONT][/RIGHT]</p></br> [CENTER] <br><p>[FONT=courier new]Рассмотрел${g('', 'а')} представленные доказательства по делу №${lawsuitNum}.</p> <p>Запрашиваю полную видеофиксацию, пояснения</p> <p>у ${g('сотрудника', 'сотрудницы')} ${CONFIG.organization} Nick_Name.</p> <p>Срок на предоставление доказательств суду — 24 часа.[/FONT]</p></br> <br><p>[SPOILER="Обязательная форма ответа на иск"] [FONT=courier new]</p><p>To the State Court of ${CONFIG.server}</p></br> <br><p>Federal Bureau of Investigation Field Office/Los Santos Police Department/Las Venturas Police Department/San Fierro Police Department/Red County Sheriff's Department (выбрать свою)</p></br> <br><p>От ${g('сотрудника', 'сотрудницы')} ${CONFIG.organization} - Имя Фамилия</p> <p>Рассмотрев обвинения в свою сторону, прикладываю соответствующие доказательства по делу и даю краткое пояснения ситуации:</p> <p>К своим словам прикладываю доказательства:</p> <p>Тайм коды:</p></br> <br>Я, ${g('гражданин', 'гражданка')} штата ${SERVER_NAME_RU}, торжественно клянусь, что предоставленные мной факты не являются сфальсифицированы и являются полностью правдивыми.</br> <br><p>Дата:</p> <p>Подпись:</p>[/FONT] [/spoiler] [/CENTER]</br> <br><p>[RIGHT][SIZE=4][FONT=courier new]${dateOnly}</p> <p>Подпись: ${CONFIG.signature}[/FONT][/SIZE][/RIGHT]</p></br>`; } },
            courtWrongFormat: { title: 'Иск не по форме', text: function(today) { const dateOnly = today.split(',')[0]; return `[CENTER][FONT=courier new][IMG width="274px"]https://i.imgur.com/y77Cwct.png[/IMG]<br>[IMG]https://i.imgur.com/03s50C0.png[/IMG][/FONT][/CENTER]<br>[RIGHT][FONT=courier new]Судейская коллегия штата ${CONFIG.server}<br>${CONFIG.rang} ${CONFIG.nickname}[/FONT][/RIGHT]<br>[CENTER][FONT=courier new]<br>Я, ${CONFIG.rang} штата ${CONFIG.server}, руководствуясь принципами справедливости, а также законами штата ${CONFIG.server}.<br><br>П О С Т А Н О В Л Я Ю<br><br>1. Закрыть исковое заявление без вынесения вердикта в связи с незнанием правил подачи искового заявления.<br><br>[SPOILER="ООС: Пояснение"]...[/SPOILER]<br><br>Приговор вступает в законную силу с момента его вынесения.<br>Дело по данному исковому делу считать закрытым с момента вынесения приговора.<br>Приговор подлежит обжалованию в [URL='https://forum.arizona-rp.com/forums/625/'][COLOR=rgb(247, 218, 100)]Кабинете Апелляции[/COLOR][/URL] в течении 5 рабочих дней.<br>Все судебные издержки по исполнению данного приговора покрываются за счет государства.<br>Судебные издержки по обжалованию приговора покрываются за счет осужденных и их законных представителей.<br><br>${dateOnly}<br> Подпись: ${CONFIG.signature}[/FONT][/CENTER]`; } },
            courtVerdictDefault: { title: 'Вердикт (Обычный)', text: function(today, lawsuitNum) { const dateOnly = today.split(',')[0]; return `[CENTER][FONT=courier new][IMG width="274px"]https://i.imgur.com/y77Cwct.png[/IMG]<br>[IMG]https://i.imgur.com/03s50C0.png[/IMG][/FONT][/CENTER]<br>[RIGHT][FONT=courier new]Судейская коллегия штата ${CONFIG.server}<br>${CONFIG.rang} ${CONFIG.nickname}[/FONT][/RIGHT]<br>[CENTER][FONT=courier new]<br>Я, ${CONFIG.rang} штата ${CONFIG.server}, руководствуясь принципами справедливости, а также законами штата ${CONFIG.server}, выношу решение по исковому заявлению №${lawsuitNum}, поступившего от ${dateOnly} от ${g('гражданина', 'гражданки')} NickName.<br><br>П О С Т А Н О В Л Я Ю<br><br>1. ...<br>2. ...<br>3. ...<br><br>Приговор вступает в законную силу с момента его вынесения.<br>Дело по данному исковому делу считать закрытым с момента вынесения приговора.<br>Приговор подлежит обжалованию в [URL='https://forum.arizona-rp.com/forums/625/'][COLOR=rgb(247, 218, 100)]Кабинете Апелляции[/COLOR][/URL] в течении 5 рабочих дней.<br>Все судебные издержки по исполнению данного приговора покрываются за счет государства.<br>Судебные издержки по обжалованию приговора покрываются за счет осужденных и их законных представителей. <br><br>${dateOnly}<br> Подпись: ${CONFIG.signature}[/FONT][/CENTER]`; } },
            courtVerdictCriminal: { title: 'Вердикт Уголовного Дела', text: function(today, lawsuitNum) { const dateOnly = today.split(',')[0]; return `[CENTER][FONT=courier new][IMG width="274px"]https://i.imgur.com/y77Cwct.png[/IMG]<br>[IMG]https://i.imgur.com/03s50C0.png[/IMG][/FONT][/CENTER]<br>[RIGHT][FONT=courier new]Судейская коллегия штата ${CONFIG.server}<br>${CONFIG.rang} ${CONFIG.nickname}[/FONT][/RIGHT]<br>[CENTER][FONT=courier new]<br>Я, ${CONFIG.rang} штата ${CONFIG.server}, руководствуясь принципами справедливости, а также законами штата ${CONFIG.server}, выношу решение по исковому заявлению №${lawsuitNum}, поступившего от ${dateOnly} от ${g('гражданина', 'гражданки')} NickName.<br><br>П О С Т А Н О В Л Я Ю<br><br>1. Признать ${g('гражданина', 'гражданку')} - NICKNAME виновным в нарушении статьи STATJA Уголовного Кодекса штата ${SERVER_NAME_RU}.<br>2. Выписать ордер на арест данного ${g('гражданина', 'гражданки')} по соответствующей статье.<br>3. Провести правомерный арест вышеупомянутого ${g('гражданина', 'гражданки')}.<br>4. Закрыть дело по решению суда.<br><br>Приговор вступает в законную силу с момента его вынесения.<br>Дело по данному исковому делу считать закрытым с момента вынесения приговора.<br>Приговор подлежит обжалованию в [URL='https://forum.arizona-rp.com/forums/625/'][COLOR=rgb(247, 218, 100)]Кабинете Апелляции[/COLOR][/URL] в течении 5 рабочих дней.<br>Все судебные издержки по исполнению данного приговора покрываются за счет государства.<br>Судебные издержки по обжалованию приговора покрываются за счет осужденных и их законных представителей. <br><br>${dateOnly}<br> Подпись: ${CONFIG.signature}[/FONT][/CENTER]`; } },
            courtVerdictFederal: { title: 'Вердикт Федерального Дела', text: function(today, lawsuitNum) { const dateOnly = today.split(',')[0]; return `[CENTER][FONT=courier new][IMG width="274px"]https://i.imgur.com/y77Cwct.png[/IMG]<br>[IMG]https://i.imgur.com/03s50C0.png[/IMG][/FONT][/CENTER]<br>[RIGHT][FONT=courier new]Судейская коллегия штата ${CONFIG.server}<br>${CONFIG.rang} ${CONFIG.nickname}[/FONT][/RIGHT]<br>[CENTER][FONT=courier new]<br>Я, ${CONFIG.rang} штата ${CONFIG.server}, руководствуясь принципами справедливости, а также законами штата ${CONFIG.server}, выношу решение по исковому заявлению №${lawsuitNum}, поступившего от ${dateOnly} от ${g('гражданина', 'гражданки')} NickName.<br><br>П О С Т А Н О В Л Я Ю<br><br>1. Признать ${g('сотрудника', 'сотрудницу')} ${CONFIG.organization} - NICKNAME виновным в нарушении статьи XX [НПА].<br>2. Вписать в личное дело сотрудника один/два дисциплинарных выговора.<br>3. Закрыть дело по решению суда.<br><br>Приговор вступает в законную силу с момента его вынесения.<br>Дело по данному исковому делу считать закрытым с момента вынесения приговора.<br>Приговор подлежит обжалованию в [URL='https://forum.arizona-rp.com/forums/625/'][COLOR=rgb(247, 218, 100)]Кабинете Апелляции[/COLOR][/URL] в течении 5 рабочих дней.<br>Все судебные издержки по исполнению данного приговора покрываются за счет государства.<br>Судебные издержки по обжалованию приговора покрываются за счет осужденных и их законных представителей. <br><br>${dateOnly}<br> Подпись: ${CONFIG.signature}[/FONT][/CENTER]`; } },
            otchetzamaGOV: { title: 'Отчёт заместителя фракции (ГОС)', text: function(today, lawsuitNum, monday) { const dateOnly = today.split(',')[0]; return `<br><p>[FONT=verdana][SIZE=5]1. Имя Фамилия: ${CONFIG.nickname}</p> <p>2. Ваша организация: ${CONFIG.organization}</p> <p>3. Ссылка на Ваш VK:</p> <p>4. Что было проделано за эту неделю [1 - 2 предложения о каждом событии]:</p> <p>5. Доказательство каждого события [по пунктам]:</p> <p>1}</p> <p>2}</p> <p>x}</p> <p>6. Работа была проделана с ${monday} по ${dateOnly}:</p> <p>7. Подпись: ${CONFIG.signature}[/SIZE][/FONT]</p></br>`; } },
            otchetlideraGOV: { title: 'Отчёт лидера фракции (ГОС)', text: function(today, lawsuitNum, monday) { const dateOnly = today.split(',')[0]; return `<br><p>[FONT=verdana][SIZE=5]1. Имя Фамилия: ${CONFIG.nickname}</p> <p>2. Ваша должность: ${CONFIG.rang} ${CONFIG.organization}</p> <p>3. Ссылка на Ваш VK:</p> <p>4. Что было проделано за эту неделю:</p> <p>5. Обязательные:</p> <p>1}</p> <p>2}</p> <p>x}</p> <p>6. Дополнительные:</p> <p>1}</p> <p>2}</p> <p>x}</p> <p>7. Доказательство каждого события (по пунктам):</p> <p>8. Работа была проделана с ${monday} по ${dateOnly}:</p> <p>9. Подпись: ${CONFIG.signature}[/SIZE][/FONT]</p></br>`; } },
            AntiBlatGOV: { title: 'Подать анти-блат', text: `<br><p>[FONT=verdana][SIZE=5]Ваш ник: ${CONFIG.nickname}.</p> <p>Ваша фракция: ${CONFIG.organization}.</p> <p>Ваша должность: ${CONFIG.rang}.</p> <p>Ник сотрудника выставленного на повышения/перевод/восстановление:</p> <p>С какого на какой ранг повышаете/переводите/восстанавливаете:</p> <p>Причина повышения сотрудника?: Отчёт/перевод/восстановление</p> <p>Доказательства проделанной работы: Ссылка на отчёт/заявление на восстановление/перевод</p> <p>Скриншот последнего повышения(/jobprogress):[/SIZE][/FONT]</p></br>` },
            PrikazMinsraUS: { title: 'Подать приказ (Министр Юстиции)', text: `<br>[CENTER][IMG width="395px"]https://i.imgur.com/IZ3EVq2.png[/IMG]</br> <br><p>[FONT=times new roman]Приказ Министерства Юстиции</p> <p>О "Наименование приказа"</p> <p>Месяц (англ.) день, 20хх #номер</p></br> <br>В соответствии со статьей 24 Главы II Конституции штата ${CONFIG.server}, п р и к а з ы в а ю:</br> <br><p>1. Текст приказа.</p> <p>2. Текст приказа.</p> <p>...</p></br> <br><p>Министр Юстиции штата ${CONFIG.server}, ${CONFIG.nickname}.</p> <p>Подпись: ${CONFIG.signature}[/FONT][/CENTER]</p></br>` },
            ViezdnieMP: { title: 'Подать выездное МП', text: function(today) { const dateOnly = today.split(',')[0]; return `<br><p>[FONT=verdana][SIZE=5]1. Ваш ник: ${CONFIG.nickname}.</p> <p>2. Ваша фракция: ${CONFIG.organization}.</p> <p>3. Ваша должность: ${CONFIG.rang}.</p> <p>4. Фотоотчет [/time]:</p> <p>5. Название выездного мероприятия:</p> <p>6. Дата: ${dateOnly}[/SIZE][/FONT]</p></br>`; } },
            PlanDeistviyMO: { title: 'Подать плановою дейтельность (МО)', text: function(today, lawsuitNum, monday) { const dateOnly = today.split(',')[0]; return `<br><p>[RIGHT][SIZE=4][FONT=courier new]Министру обороны - Имя Фамилия;</p> <p>от ${CONFIG.rangGenitive}, ${CONFIG.nickname}.[/FONT][/SIZE][/RIGHT] [CENTER]</p> <p>[SIZE=4][FONT=courier new]Прилагаемый отчет:</p></br> <br><p>Я, ${CONFIG.rang}, ${CONFIG.nickname}, выполнил${g('', 'а')} плановую деятельность, данную вами, на неделю (с ${monday} по ${dateOnly}).</p> <p>К отчёту прилагаю доказательства проделанной работы. Прошу ознакомиться и сделать проверку.</p> <p>*проделанная работа по пунктам с доказательствами*[/FONT][/SIZE]</p> [/CENTER]</br> <br><p>[SIZE=4][FONT=courier new]Дата: ${dateOnly}</p> <p>Подпись: ${CONFIG.signature}[/FONT][/SIZE]</p></br>`; } },
            MZRevision: { title: 'Подать ревизию/проверку', text: function(today) { const dateOnly = today.split(',')[0]; return `<br><p>[FONT=verdana][SIZE=5]1. Ваш ник: ${CONFIG.nickname}.</p> <p>2. Ваша фракция: ${CONFIG.organization}</p> <p>3. Ваша должность:${CONFIG.rang}</p> <p>4. Где проводили ревизию/проверку пожарной безопасности:</p> <p>5. Фотоотчет [/time]:</p> <p>6. Дата: ${dateOnly}[/SIZE][/FONT]</p></br>`; } },
            MZProverka: { title: 'Подать проверку гос. фракции', text: function(today) { const dateOnly = today.split(',')[0]; return `<br><p>[FONT=verdana][SIZE=5]1. Ваш ник: ${CONFIG.nickname}.</p> <p>2. Ваша фракция: ${CONFIG.organization}</p> <p>3. Ваша должность:${CONFIG.rang}</p> <p>4. Название гос. организации, которой проводили проверку:</p> <p>5. Фотоотчет [/time]:</p> <p>6. Дата: ${dateOnly}[/SIZE][/FONT]</p></br>`; } },
            otchetlideraNelegal: { title: 'Отчёт лидера фракции', text: `<br><p>[FONT=verdana][SIZE=5]1. Игровой Nick_Name: ${CONFIG.NonRPnickname}</p> <p>2. Лидер какой Bы банды: ${CONFIG.rang} ${CONFIG.organization}</p> <p>3. Скриншот статистики:</p> <p>4. Скриншоты /lmenu и общака:</p> <p>5. Что сделано за неделю?(краткое описание работы):</p> <p>6. Док-ва проделанной работы:</p> <p>7. Дополнительная работа (если нет - пишите нет)[/SIZE][/FONT]</p></br>` },
            NelegalPolBali: { title: 'Получить балы', text: `<br><p>[FONT=verdana][SIZE=5]1. Игровой ник: ${CONFIG.NonRPnickname}</p> <p>2. Лидер какой вы банды: ${CONFIG.rang} ${CONFIG.organization}</p> <p>3. Что сделано?:</p> <p>4. Док-ва проделанной работы:[/SIZE][/FONT]</p></br>` },
            NelegalPotBali: { title: 'Потратить балы', text: `<br><p>[FONT=verdana][SIZE=5]1. Игровой ник: ${CONFIG.NonRPnickname}</p> <p>2. Лидер какой вы банды: ${CONFIG.rang} ${CONFIG.organization}</p> <p>3. На что вы хотите потратить:[/SIZE][/FONT]</p></br>` },
            NelegalMoroz: { title: 'Взять мороз', text: `<br><p>[FONT=verdana][SIZE=5]1. Ник лидера: ${CONFIG.NonRPnickname}</p> <p>2. Название банды: ${CONFIG.organization}</p> <p>3. Какой был взят мороз: краткосрочный/долгосрочный</p> <p>4. На какой срок был взят мороз:</p> <p>5. Скриншот взятия мороза через общак с /time:[/SIZE][/FONT]</p></br>` },
            NelegalNeaktiv: { title: 'Взять Неактив', needsSecondDate: true, text: function(today, lawsuitNum, monday, secondDate) { const dateOnly = today.split(',')[0]; return `<br><p>[FONT=verdana][SIZE=5]1. Ваш ник: ${CONFIG.NonRPnickname}</p> <p>2. Банда: ${CONFIG.organization}</p> <p>3. Срок неактива : С ${dateOnly} по ${secondDate}</p> <p>4. Причина:[/SIZE][/FONT]</p></br>`; } },
            GiveOpra: { title: 'Дать опру (капта/смуга/стрелы/кб)', text: `<br><p>[FONT=verdana][SIZE=5]1. Ваш NickName: ${CONFIG.NonRPnickname}</p> <p>2. Ваша банда/мафия: ${CONFIG.organization}</p> <p>3. Причина варна/бана/джайла:</p> <p>4. Кем выдано наказание:</p> <p>5. Опра:[/SIZE][/FONT]</p></br>` },
            GetTerra: { title: 'Выдача территории за нарушения', text: `<br><p>[FONT=verdana][SIZE=5]1. Ваш NickName: ${CONFIG.NonRPnickname}</p> <p>2. Ваша организация и должность: ${CONFIG.rang} ${CONFIG.organization}</p> <p>3. Организация, от которой нужно отдать территорию:</p> <p>4. Док-ва выдачи наказания:</p> <p>5. Нарушение за которое вам должны отдать территорию:[/SIZE][/FONT]</p></br>` },
            GetBiz: { title: 'Выдача бизнеса за нарушения', text: `<br><p>[FONT=verdana][SIZE=5]Ваш игровой Ник: ${CONFIG.NonRPnickname}</p> <p>Ваша мафия и должность: ${CONFIG.rang} ${CONFIG.organization}</p> <p>Мафия от которой нужно забрать бизнес:</p> <p>Доказательства:[/SIZE][/FONT]</p></br>` },
            takethechilloff: { title: 'Снять мороз', text: `<br><p>[FONT=verdana][SIZE=5]1. Ваш NickName: ${CONFIG.NonRPnickname}.</p> <p>2. Лидер какой вы фракции: ${CONFIG.organization}.</p> <p>3. Доказательство выполненной работы:</p> <p>Дипломатия: *ССЫЛКА на одобренную тему*.</p> <p>Постановление Зама: *Скриншот одобренного Анти-Блата*.</p> <p>Прикрытие: *Скриншот одобренного Прикрытия*.</p> <p>Форум: *ССЫЛКА на форум своей фракции*[/SIZE][/FONT]</p></br>` },
            NelegalPolBaliMaf: { title: 'Получить балы', text: `<br><p>[FONT=verdana][SIZE=5]1. Игровой ник: ${CONFIG.NonRPnickname}</p> <p>2. Лидер какой вы мафии: ${CONFIG.rang} ${CONFIG.organization}</p> <p>3. Что сделано?:</p> <p>4. Док-ва проделанной работы:[/SIZE][/FONT]</p></br>` },
            NelegalPotBaliMaf: { title: 'Потратить балы', text: `<br><p>[FONT=verdana][SIZE=5]1. Игровой ник: ${CONFIG.NonRPnickname}</p> <p>2. Лидер какой вы мафии: ${CONFIG.rang} ${CONFIG.organization}</p> <p>3. На что вы хотите потратить:[/SIZE][/FONT]</p></br>` },
            otchetlideraNelegalMaf: { title: 'Отчёт лидера фракции', text: `<br><p>[FONT=verdana][SIZE=5]1. Игровой Nick_Name: ${CONFIG.NonRPnickname}</p> <p>2. Лидер какой вы мафии: ${CONFIG.rang} ${CONFIG.organization}</p> <p>3. Скриншот статистики:</p> <p>4. Скриншоты /lmenu и общака:</p> <p>5. Что сделано за неделю?(краткое описание работы):</p> <p>6. Док-ва проделанной работы:</p> <p>7. Дополнительная работа (если нет - пишите нет)[/SIZE][/FONT]</p></br>` },
            SnatVigPoZadaniu: { title: 'Снять выговор по заданию', text: `<br><p>[FONT=verdana][SIZE=5]Nick Name: ${CONFIG.NonRPnickname}.</p> <p>Мафия: ${CONFIG.organization}.</p> <p>Строгих сейчас:</p> <p>Строгих снимаю:</p> <p>Проделанная работа:[/SIZE][/FONT]</p></br>` },
            ZabitDiploma: { title: 'Забить дипломатию', text: `<br><p>[FONT=verdana][SIZE=5]1. Ваш игровой никнейм: ${CONFIG.nickname}.</p> <p>2. Лидером какой мафии Вы являетесь: ${CONFIG.organization}.</p> <p>3. С какой фракцией заключили:</p> <p>4. Исход встречи: Союз/Нейтралитет/Война.</p> <p>5. Недвижимость, потраченная на дипломатию: (Номера бизнесов).</p> <p>6. Видеозапись:[/SIZE][/FONT]</p></br>` }
        };

        const MENU_STRUCTURE = {
            admin: {
                title: '👑 Администратор',
                templates: [REPLIES.verdict, REPLIES.jbadm, REPLIES.jbadmError, REPLIES.inReview, REPLIES.requestProof, REPLIES.wrongFormat, REPLIES.transferred]
            },
            court: {
                title: '⚖️ Суд',
                subcategories: {
                    court_answers: { title: '⚖️ Ответы', templates: [REPLIES.takeLawsuit, REPLIES.requestExplanations, REPLIES.courtWrongFormat, REPLIES.courtVerdictDefault, REPLIES.courtVerdictCriminal, REPLIES.courtVerdictFederal] },
                    court_extras: { title: '⚙️ Доп. для вердикта', templates: EXTRA_OPTIONS },
                    court_orgs: { title: '🏢 Организации', templates: ORG_NAMES }
                }
            },
            pd: {
                title: '🚓 Полицейский департамент',
                templates: [REPLIES.pdDefault, REPLIES.playerDefault, REPLIES.motionDefendant, REPLIES.addmotionDefendant, REPLIES.addmotionPlaintiff, REPLIES.addlawyerPetitionFromPlaintiff, REPLIES.addDefendantPetitionFromPlaintiff]
            },
            lawyer: {
                title: '👤 Адвокат',
                templates: [REPLIES.playerDefault, REPLIES.lawyerPetition, REPLIES.motionPlaintiff, REPLIES.motionDefendant, REPLIES.addmotionDefendant, REPLIES.addmotionPlaintiff, REPLIES.addlawyerPetition, REPLIES.addlawyerPetitionFromPlaintiff, REPLIES.addDefendantPetitionFromPlaintiff]
            },
            ghetto: {
                title: '📂 Остальное',
                templates: [REPLIES.ghettoDefault, REPLIES.GiveOpra]
            },
            leaderZams: {
                title: '🍺 Лидер/Зам',
                subcategories: {
                    gos: { title: '🏛 Гос', templates: [REPLIES.otchetzamaGOV, REPLIES.otchetlideraGOV, REPLIES.AntiBlatGOV, REPLIES.PrikazMinsraUS, REPLIES.ViezdnieMP, REPLIES.PlanDeistviyMO, REPLIES.MZProverka, REPLIES.MZRevision] },
                    ghetto: { title: '🔫 Гетто', templates: [REPLIES.otchetlideraNelegal, REPLIES.NelegalPolBali, REPLIES.NelegalPotBali, REPLIES.NelegalMoroz, REPLIES.NelegalNeaktiv, REPLIES.GetTerra] },
                    mafia: { title: '🕴 Мафия', templates: [REPLIES.otchetlideraNelegalMaf, REPLIES.GetBiz, REPLIES.takethechilloff, REPLIES.NelegalPolBaliMaf, REPLIES.NelegalPotBaliMaf, REPLIES.SnatVigPoZadaniu, REPLIES.ZabitDiploma] }
                }
            }
        };

        const HOTKEYS = {
            F1: REPLIES.inReview,
            F2: REPLIES.transferred,
            F3: REPLIES.wrongFormat,
            F4: REPLIES.verdict
        };

        return { MENU: MENU_STRUCTURE, HOTKEYS: HOTKEYS };
    };
})();